### ISSUE TITLE
solc 0.8.20 support and new release

### ISSUE THREAD

**Issue by mattsse** [ethers-rs/svm-rs#84]
ref https://github.com/foundry-rs/foundry/issues/4916

https://github.com/nikitastupin/solc landed 0.8.20 so no more blockers

**Comment by dantaik** [comment]
We are also waiting for this issue to be resolved:)

**Comment by Evalir** [comment]
ref https://github.com/ethers-rs/svm-rs/pull/86 — this is done, so closing!
