### ISSUE TITLE
forge build result in Solc Error:  "Unknown version provided"

### ISSUE THREAD

**Issue by spilehchiha** [ethers-rs/svm-rs#85]
``I'm on an M2 MacBook with macOS 13.3.1 (a) (22E772610a) installed.

After successfully compiling the contracts, I try to run `forge build` and this is the error I get:

```
[⠊] Compiling...
[⠑] Installing solc version 0.8.20
[⠘] Failed to install solc 0.8.20: Unknown version provided
Error: 
Unknown version provided
```

I thank you for your time and attention.

**Comment by mattsse** [comment]
this is a dup of #84

**Comment by Evalir** [comment]
Closing as #84 is done also
